version: 2

conda:
    environment: environment.yml

sphinx:
    configuration: docs/conf.py

build:
    image: latest

formats:
  - pdf

python:
    install:
      - method: pip
        path: .
        extra_requirements:
         - docs